INSERT INTO categories (id, title) VALUES (1, 'ACTION');
INSERT INTO categories (id, title) VALUES (2, 'PLATFORMER');
INSERT INTO categories (id, title) VALUES (3, 'SHOOTER');
INSERT INTO categories (id, title) VALUES (4, 'FIGHTING');
INSERT INTO categories (id, title) VALUES (5, 'BEAT EM'' UP');
INSERT INTO categories (id, title) VALUES (6, 'STEALTH');
INSERT INTO categories (id, title) VALUES (7, 'SURVIVAL');
INSERT INTO categories (id, title) VALUES (8, 'RHYTHM');
INSERT INTO categories (id, title) VALUES (9, 'BATTLE ROYALE');
INSERT INTO categories (id, title) VALUES (10, 'ACTION-ADVENTURE');
INSERT INTO categories (id, title) VALUES (11, 'SURVIVAL HORROR');
INSERT INTO categories (id, title) VALUES (12, 'METROIDVANIA');
INSERT INTO categories (id, title) VALUES (13, 'ADVENTURE');
INSERT INTO categories (id, title) VALUES (14, 'TEXT ADVENTURE');
INSERT INTO categories (id, title) VALUES (15, 'GRAPHIC ADVENTURE');
INSERT INTO categories (id, title) VALUES (16, 'VISUAL NOVEL');
INSERT INTO categories (id, title) VALUES (17, 'INTERACTIVE MOVIE');
INSERT INTO categories (id, title) VALUES (18, 'REAL-TIME 3D ADVENTURE');
INSERT INTO categories (id, title) VALUES (19, 'ROLE-PLAYING');
INSERT INTO categories (id, title) VALUES (20, 'ACTION RPG');
INSERT INTO categories (id, title) VALUES (21, 'MMORPG');
INSERT INTO categories (id, title) VALUES (22, 'ROGUELIKE');
INSERT INTO categories (id, title) VALUES (23, 'TACTICAL RPG');
INSERT INTO categories (id, title) VALUES (24, 'SANDBOX RPG');
INSERT INTO categories (id, title) VALUES (25, 'FIRST-PERSON PARTY-BASED RPG');
INSERT INTO categories (id, title) VALUES (26, 'JRPG');
INSERT INTO categories (id, title) VALUES (27, 'MONSTER TAMER');
INSERT INTO categories (id, title) VALUES (28, 'SIMULATION');
INSERT INTO categories (id, title) VALUES (29, 'CONSTRUCTION AND MANAGEMENT');
INSERT INTO categories (id, title) VALUES (30, 'LIFE SIMULATION');
INSERT INTO categories (id, title) VALUES (31, 'VEHICLE SIMULATION');
INSERT INTO categories (id, title) VALUES (32, 'STRATEGY');
INSERT INTO categories (id, title) VALUES (33, '4X GAME');
INSERT INTO categories (id, title) VALUES (34, 'ARTILLERY');
INSERT INTO categories (id, title) VALUES (35, 'AUTO BATTLER (AUTO CHESS)');
INSERT INTO categories (id, title) VALUES (36, 'MOBA');
INSERT INTO categories (id, title) VALUES (37, 'REAL-TIME STRATEGY');
INSERT INTO categories (id, title) VALUES (38, 'REAL-TIME TACTICS');
INSERT INTO categories (id, title) VALUES (39, 'TURN-BASED TACTICS');
INSERT INTO categories (id, title) VALUES (40, 'WARGAME');
INSERT INTO categories (id, title) VALUES (41, 'GRAND STRATEGY WARGAME');
INSERT INTO categories (id, title) VALUES (42, 'SPORTS');
INSERT INTO categories (id, title) VALUES (43, 'RACING');
INSERT INTO categories (id, title) VALUES (44, 'SPORTS');
INSERT INTO categories (id, title) VALUES (45, 'COMPETITIVE');
INSERT INTO categories (id, title) VALUES (46, 'SPORTS-BASED FIGHTING');
INSERT INTO categories (id, title) VALUES (47, 'MMO');
INSERT INTO categories (id, title) VALUES (48, 'BOARD');
INSERT INTO categories (id, title) VALUES (49, 'CARD');
INSERT INTO categories (id, title) VALUES (50, 'CASINO');
INSERT INTO categories (id, title) VALUES (51, 'CASUAL');
INSERT INTO categories (id, title) VALUES (52, 'GACHA');
INSERT INTO categories (id, title) VALUES (53, 'HORROR');
INSERT INTO categories (id, title) VALUES (54, 'IDLE');
INSERT INTO categories (id, title) VALUES (55, 'LOGIC');
INSERT INTO categories (id, title) VALUES (56, 'PARTY');
INSERT INTO categories (id, title) VALUES (57, 'PHOTOGRAPHY');
INSERT INTO categories (id, title) VALUES (58, 'PROGRAMMING');
INSERT INTO categories (id, title) VALUES (59, 'SOCIAL DEDUCTION');
INSERT INTO categories (id, title) VALUES (60, 'TRIVIA');
INSERT INTO categories (id, title) VALUES (61, 'TYPING');
INSERT INTO categories (id, title) VALUES (62, 'ART');
INSERT INTO categories (id, title) VALUES (63, 'CASUAL');
INSERT INTO categories (id, title) VALUES (64, 'EDUCATIONAL');
INSERT INTO categories (id, title) VALUES (65, 'SANDBOX');
INSERT INTO categories (id, title) VALUES (66, 'CREATIVE');
INSERT INTO categories (id, title) VALUES (67, 'OPEN WORLD');
INSERT INTO categories (id, title) VALUES (68, 'CITY BUILDER');
INSERT INTO categories (id, title) VALUES (69, 'MULTIPLAYER');
INSERT INTO categories (id, title) VALUES (70, 'PRECISION PLATFORMER');
INSERT INTO categories (id, title) VALUES (71, 'DIFFICULT');
INSERT INTO categories (id, title) VALUES (72, 'GREAT SOUNDTRACK');
INSERT INTO categories (id, title) VALUES (73, 'PIXEL GRAPHICS');
INSERT INTO categories (id, title) VALUES (74, 'INDIE');
INSERT INTO categories (id, title) VALUES (75, 'RPG');
INSERT INTO categories (id, title) VALUES (76, 'SOULS-LIKE');
INSERT INTO categories (id, title) VALUES (77, 'FIRST-PERSON');
INSERT INTO categories (id, title) VALUES (78, 'SINGLEPLAYER');
INSERT INTO categories (id, title) VALUES (79, 'PUZZLE');
INSERT INTO categories (id, title) VALUES (80, 'FIRST-PERSON SHOOTER');
INSERT INTO categories (id, title) VALUES (81, 'TACTICAL');
INSERT INTO categories (id, title) VALUES (82, 'TEAM-BASED');
INSERT INTO categories (id, title) VALUES (83, 'FARMING SIM');
INSERT INTO categories (id, title) VALUES (84, 'CYBERPUNK');
INSERT INTO categories (id, title) VALUES (85, 'SCI-FI');
INSERT INTO categories (id, title) VALUES (86, 'DARK FANTASY');
INSERT INTO categories (id, title) VALUES (87, 'STORY RICH');
INSERT INTO categories (id, title) VALUES (88, 'ATMOSPHERIC');
INSERT INTO categories (id, title) VALUES (89, 'CARTOON');
INSERT INTO categories (id, title) VALUES (90, 'FUNNY');
INSERT INTO categories (id, title) VALUES (91, 'ONLINE CO-OP');