insert into categories (id, title) values (1, 'ESTRATEGIA');
insert into categories (id, title) values (2, 'PIXELADOS');
insert into categories (id, title) values (3, 'CONSTRUCTOR DE CIUDADES');
insert into categories (id, title) values (4, 'ACCIÓN');
insert into categories (id, title) values (5, 'PLATAFORMAS');
insert into categories (id, title) values (6, 'DIFÍCIL');
insert into categories (id, title) values (7, 'INDIE');
insert into categories (id, title) values (8, 'ROGUELIKE');
insert into categories (id, title) values (9, 'DEPORTES');
insert into categories (id, title) values (10, 'SANDBOX');
insert into categories (id, title) values (11, 'TERROR');
insert into categories (id, title) values (12, '2D');
insert into categories (id, title) values (13, '3D');
insert into categories (id, title) values (14, 'MUNDO ABIERTO');
insert into categories (id, title) values (15, 'FREE TO PLAY');
insert into categories (id, title) values (16, 'AVENTURAS');
insert into categories (id, title) values (17, 'SIMULADORES');
insert into categories (id, title) values (18, 'COOPERATIVO');
insert into categories (id, title) values (19, 'MULTIJUGADOR');
insert into categories (id, title) values (20, 'SURVIVAL');
insert into categories (id, title) values (21, 'SHOOTER');
insert into categories (id, title) values (22, 'RPG');
insert into categories (id, title) values (23, 'CARTAS');
insert into categories (id, title) values (24, 'MOBA');